apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cert-julip
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - cert-julip
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes
  - routes/custom-host
  verbs:
  - '*'
- apiGroups:
  - certmanager.k8s.io
  attributeRestrictions: null
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
